<?php

declare(strict_types=1);

/*
 * This file is part of PHP CS Fixer.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *     Dariusz Rumiński <dariusz.ruminski@gmail.com>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

namespace PhpCsFixer\Tests\Fixer\ArrayNotation;

use PhpCsFixer\Fixer\ArrayNotation\MultilineArrayFixer;
use PhpCsFixer\Tests\Test\AbstractFixerTestCase;
use PhpCsFixer\WhitespacesFixerConfig;
use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\DataProvider;

/**
 * @internal
 *
 * @covers \PhpCsFixer\Fixer\ArrayNotation\MultilineArrayFixer
 *
 * @extends AbstractFixerTestCase<\PhpCsFixer\Fixer\ArrayNotation\MultilineArrayFixer>
 *
 * @phpstan-import-type _AutogeneratedInputConfiguration from \PhpCsFixer\Fixer\ArrayNotation\MultilineArrayFixer
 *
 * @no-named-arguments Parameter names are not covered by the backward compatibility promise.
 */
#[CoversClass(MultilineArrayFixer::class)]
final class MultilineArrayFixerTest extends AbstractFixerTestCase
{
    /**
     * @dataProvider provideFixCases
     *
     * @param _AutogeneratedInputConfiguration $configuration
     */
    #[DataProvider('provideFixCases')]
    public function testFix(string $expected, ?string $input = null, ?array $configuration = null): void
    {
        if (null !== $configuration) {
            $this->fixer->configure($configuration);
        }

        $this->doTest($expected, $input);
    }

    /**
     * @return iterable<string, array{0: string, 1?: null|string, 2?: _AutogeneratedInputConfiguration}>
     */
    public static function provideFixCases(): iterable
    {
        yield 'multiple elements get split' => [
            "<?php\n\$foo = [\n    'a',\n    'b',\n    'c'\n];\n",
            "<?php\n\$foo = ['a', 'b', 'c'];\n",
        ];

        yield 'single element is left untouched' => [
            "<?php\n\$foo = ['a'];\n",
        ];

        yield 'empty array is left untouched' => [
            "<?php\n\$foo = [];\n",
        ];

        yield 'keyed elements get split' => [
            "<?php\n\$foo = [\n    'a' => 1,\n    'b' => 2\n];\n",
            "<?php\n\$foo = ['a' => 1, 'b' => 2];\n",
        ];

        yield 'old style array syntax' => [
            "<?php\n\$foo = array(\n    'a',\n    'b'\n);\n",
            "<?php\n\$foo = array('a', 'b');\n",
        ];

        yield 'trailing comma is kept' => [
            "<?php\n\$foo = [\n    'a',\n    'b',\n];\n",
            "<?php\n\$foo = ['a', 'b',];\n",
        ];

        yield 'already multiline gets normalized' => [
            "<?php\n\$foo = [\n    'a',\n    'b',\n];\n",
            "<?php\n\$foo = [\n  'a',\n        'b',\n];\n",
        ];

        yield 'indentation is kept' => [
            "<?php\nclass C {\n    public function f() {\n        \$foo = [\n            'a',\n            'b'\n        ];\n    }\n}\n",
            "<?php\nclass C {\n    public function f() {\n        \$foo = ['a', 'b'];\n    }\n}\n",
        ];

        yield 'nested arrays are split' => [
            "<?php\n\$foo = [\n    'a',\n    'b',\n    [\n        'c',\n        'd'\n    ]\n];\n",
            "<?php\n\$foo = ['a', 'b', ['c', 'd']];\n",
        ];

        yield 'commas of nested calls are not counted' => [
            "<?php\n\$foo = [foo(1, 2)];\n",
        ];

        yield 'nested call is kept on one line' => [
            "<?php\n\$foo = [\n    foo(1, 2),\n    'b'\n];\n",
            "<?php\n\$foo = [foo(1, 2), 'b'];\n",
        ];

        yield 'arrays with comments are left untouched' => [
            "<?php\n\$foo = [/* x */ 'a', 'b'];\n",
        ];

        yield 'min_items leaves smaller arrays untouched' => [
            "<?php\n\$foo = ['a', 'b', 'c'];\n",
            null,
            ['min_items' => 4],
        ];

        yield 'min_items splits arrays at threshold' => [
            "<?php\n\$foo = [\n    'a',\n    'b',\n    'c'\n];\n",
            "<?php\n\$foo = ['a', 'b', 'c'];\n",
            ['min_items' => 3],
        ];

        yield 'min_items of one splits single element arrays' => [
            "<?php\n\$foo = [\n    'a'\n];\n",
            "<?php\n\$foo = ['a'];\n",
            ['min_items' => 1],
        ];

        yield 'variables_only splits assigned arrays' => [
            "<?php\n\$foo = [\n    'a',\n    'b'\n];\n",
            "<?php\n\$foo = ['a', 'b'];\n",
            ['variables_only' => true],
        ];

        yield 'variables_only leaves argument arrays untouched' => [
            "<?php\nbar(['a', 'b']);\n",
            null,
            ['variables_only' => true],
        ];

        yield 'variables_only with mixed usage' => [
            "<?php\nbar(['a', 'b']);\n\$foo = [\n    'a',\n    'b'\n];\n",
            "<?php\nbar(['a', 'b']);\n\$foo = ['a', 'b'];\n",
            ['variables_only' => true],
        ];
    }

    /**
     * @dataProvider provideWithWhitespacesConfigCases
     */
    #[DataProvider('provideWithWhitespacesConfigCases')]
    public function testWithWhitespacesConfig(string $expected, ?string $input = null): void
    {
        $this->fixer->setWhitespacesConfig(new WhitespacesFixerConfig("\t"));

        $this->doTest($expected, $input);
    }

    /**
     * @return iterable<int, array{0: string, 1?: null|string}>
     */
    public static function provideWithWhitespacesConfigCases(): iterable
    {
        yield [
            "<?php\n\$foo = [\n\t'a',\n\t'b'\n];\n",
            "<?php\n\$foo = ['a', 'b'];\n",
        ];
    }
}
